"""Add AI generated content columns

Revision ID: 31475a41f572
Revises: 
Create Date: 2024-10-29 23:28:11.792663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31475a41f572'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('websites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('related_topics', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_generated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('websites', schema=None) as batch_op:
        batch_op.drop_column('last_generated')
        batch_op.drop_column('meta_description')
        batch_op.drop_column('related_topics')
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
